@startuml
left to right direction

actor "Cliente registrato" as C
actor Sistema as S
actor Admin as A
actor Banca as B

' actor Stampe as ST

rectangle "Cliente registrato" {
    C --> (Autenticarsi)
    C --> (Noleggia)
    C --> (Consegnare)
    C --> (Visualizzare Mappa)
}
rectangle Banca {
    B --> (Gestione richiesta pagamento)
}
rectangle Visualizza{
    (visualizza informazioni)
}
(Cliente registrato)-->(Visualizza)
' gestisce transazioni tra utente e sistema
rectangle "Sistema Centrale" {
    S --> (Calcoli per monitoraggio)
    S --> (Tariffazione servizio)
    S --> (Manutenzione)
    S --> (Richiesta denaro alla banca)
}
rectangle "richiesta denaro a banca"{
    (Invio richiesta alla banca)
    (Ricezione risposta da banca)
}
(Richiesta denaro alla banca) --> (richiesta denaro a banca)
rectangle "Admin" {
    A --> (Monitoraggio)
    A --> (Registra)
    A --> (Manutenzione)
}
rectangle "Stampe" {
    (stampa operazioni per ogni user)
    (stampa operazioni per goni stazione)
    (stampa posizione bici noleggiate)
    (stampa bici non consegnate)
    (stampa bici che necessitano manutenzione)
}
' (C) --> (Visualizzare Mappa) : <<include>>
(Monitoraggio) --> (Stampe)
@enduml
